# === AI Research Feed v3 configuration ===

# Global filters
lookback_days: 7

# Keywords
include_keywords:
  - adversarial
  - "prompt injection"
  - jailbreak
  - backdoor
  - watermark
  - "model stealing"
  - "data poisoning"
  - federated
  - robust
  - secure
  - privacy
  - alignment
  - interpretability

exclude_keywords:
  - survey
  - tutorial

priority_authors:
  - "Nicolas Papernot"
  - "Ian Goodfellow"
  - "Dawn Song"
  - "Hyrum Anderson"
  - "Battista Biggio"
  - "Yevgeniy Vorobeychik"

ui:
  default_source: "All"
  show_abstract_default: true

sources:
  arxiv:
    enabled: true
    categories: ["cs.AI", "cs.LG", "cs.CL", "cs.CR"]
    max_results_per_category: 100

  reddit:
    enabled: true
    subreddits: ["MachineLearning", "MLQuestions", "netsec", "PromptEngineering"]
    include_keywords: []
    exclude_keywords: ["hiring", "job", "weekly", "who is hiring", "project showcase", "beginner thread"]
    preview_chars: 300

  openreview:
    enabled: true
    venues: ["NeurIPS 2024", "ICLR 2025", "ICML 2025"]
    limit_per_venue: 75

  acl:
    enabled: true
    feeds:
      - "https://aclanthology.org/events/acl-2024.atom"
      - "https://aclanthology.org/events/emnlp-2024.atom"
      - "https://aclanthology.org/events/naacl-2024.atom"
