# === AI Research Feed v3 configuration ===

# Global filters
lookback_days: 1
lookback_hours: 24

# Keywords
include_keywords:
  - "adversarial"
  - "prompt injection"
  - "jailbreak"
  - "backdoor"
  - "watermark"
  - "model stealing"
  - "data poisoning"
  - "federated"
  - "robust"
  - "secure"
  - "privacy"
  - "alignment"
  - "interpretability"

exclude_keywords:
  - "survey"
  - "tutorial"

priority_authors:
  - "Nicolas Papernot"
  - "Ian Goodfellow"
  - "Dawn Song"
  - "Hyrum Anderson"
  - "Battista Biggio"
  - "Yevgeniy Vorobeychik"

ui:
  default_source: "All"
  show_abstract_default: true

sources:
  arxiv:
    enabled: true
    categories: ["cs.AI", "cs.LG", "cs.CL", "cs.CR"]
    max_results_per_category: 2000
    fetch_all: false
    max_pages_per_category: 1000
    request_pause_seconds: 3.0
    include_keywords:
      [
        "adversarial",
        "prompt injection",
        "jailbreak",
        "backdoor",
        "data poisoning",
        "LLM",
        "Large Language Model",
        "ChatGPT",
        "Gemini",
        "DeepSeek",
        "Agent",
        "Agency",
        "Large Multimodal Model",
        "LMM",
        "federated",
        "secure",
        "privacy",
        "alignment",
        "interpretability",
        "uncertainty",
        "blockchain",
        "experts",
        "expert",
        "agents",
        "mixture",
        "judge",
      ]
    exclude_keywords:
      [
        "hiring",
        "job",
        "weekly",
        "who is hiring",
        "project showcase",
        "beginner thread",
      ]

  reddit:
    enabled: true
    subreddits:
      [
        "MachineLearning",
        "MLQuestions",
        "netsec",
        "PromptEngineering",
        "LLMDevs",
        "ArtificialIntelligence",
      ]
    max_results_per_subreddit: 100
    include_keywords: []
    exclude_keywords:
      [
        "hiring",
        "job",
        "weekly",
        "who is hiring",
        "project showcase",
        "beginner thread",
      ]
    preview_chars: 300

  openreview:
    enabled: true
    venues: ["NeurIPS 2024", "ICLR 2025", "ICML 2025"]
    limit_per_venue: 75

  acl:
    enabled: true
    feeds:
      - "https://aclanthology.org/events/acl-2024.atom"
      - "https://aclanthology.org/events/emnlp-2024.atom"
      - "https://aclanthology.org/events/naacl-2024.atom"

  hn:
    enabled: true
    # frontpage, newest, best — pick any hnrss feeds you like
    feeds:
      - "https://hnrss.org/frontpage"
      # - "https://hnrss.org/newest"
      # - "https://hnrss.org/best"
    include_keywords: []
    exclude_keywords: ["who is hiring", "freelance"]

  hackernoon:
    enabled: true
    feeds:
      - "https://hackernoon.com/feed"
    include_keywords: []
    exclude_keywords: ["sponsored", "partner"]

email:
  max_per_source: none # 0 / "" / "none" => unlimited
