name: Daily Digest (Outlook SMTP)
on:
  schedule:
    - cron: "0 7 * * *" # 07:00 UTC = 09:00 Europe/Amsterdam
  workflow_dispatch: {}

jobs:
  digest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r requirements.txt
      - env:
          OUTLOOK_USER: ${{ secrets.OUTLOOK_USER }}
          OUTLOOK_PASSWORD: ${{ secrets.OUTLOOK_PASSWORD }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }} # optional; defaults to OUTLOOK_USER
        run: python daily_digest.py
